feat(scripts): check for required tools and reorder options

diff --git a/home/dot_config/scripts/executable_compress_vid b/home/dot_config/scripts/executable_compress_vid
--- a/home/dot_config/scripts/executable_compress_vid
+++ b/home/dot_config/scripts/executable_compress_vid
@@ -5,11 +5,11 @@ set -euo pipefail
 help() {
   printf "\033[1mUsage: compress_vid [OPTIONS] <input_files>\033[0m\n\n"
   printf "\033[1m\033[4mOptions:\033[0m\n"
-  printf "  \033[1m-h, --help\033[0m\t\tDisplay this help message and exit\n"
-  printf "  \033[1m-s, --size\033[0m <size>\tTarget size in MB (default: 8)\n"
-  printf "  \033[1m-t, --tolerance\033[0m <tolerance>\tTolerance percentage (default: 10)\n"
-  printf "  \033[1m-c, --cpu\033[0m <cpu_count>\tNumber of CPU cores to use (default: half of available cores)\n"
-  printf "  \033[1m-o, --output\033[0m <output>\tOutput file name (default: input file name with .mp4)\n\n"
+  printf "  \033[1m--help, -h\033[0m\t\t\tDisplay this help message and exit\n"
+  printf "  \033[1m--size, -s\033[0m <size>\t\tTarget size in MB (default: 8)\n"
+  printf "  \033[1m--tolerance, -t\033[0m <tolerance>\tTolerance percentage (default: 10)\n"
+  printf "  \033[1m--cpu, -c\033[0m <cpu_count>\t\tNumber of CPU cores to use (default: half of available cores)\n"
+  printf "  \033[1m--output, -o\033[0m <output>\t\tOutput file name (default: input file name with .crushed.mp4)\n\n"
   printf "\033[1m\033[4mExamples:\033[0m\n"
   printf '  $ compress_vid -s 5 video.mp4\n'
   printf '  $ compress_vid --size 10 -t 5 video.mkv\n'
@@ -26,6 +26,7 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
   exit 0
 fi
 
+require=("ffmpeg" "ffprobe" "bc")
 size=8                      # Default target size in MB
 tolerance=10                # Default tolerance percentage
 cpu_count=$(($(nproc) / 2)) # Default to half of available CPU cores
@@ -165,6 +166,13 @@ if [ ${#input_files[@]} -eq 0 ]; then
   help
   exit 1
 fi
+
+for cmd in "${require[@]}"; do
+  if ! command -v "$cmd" &>/dev/null; then
+    echo "Error: Required command '$cmd' is not installed."
+    exit 1
+  fi
+done
 
 for file in "${input_files[@]}"; do
   echo "using $cpu_count CPU cores"
diff --git a/home/dot_config/scripts/executable_convert_img b/home/dot_config/scripts/executable_convert_img
--- a/home/dot_config/scripts/executable_convert_img
+++ b/home/dot_config/scripts/executable_convert_img
@@ -5,8 +5,8 @@ set -euo pipefail
 help() {
   printf "\033[1mUsage: convert_img [OPTIONS] <input_files>\033[0m\n\n"
   printf "\033[1m\033[4mOptions:\033[0m\n"
-  printf "  \033[1m-h, --help\033[0m\t\tDisplay this help message and exit\n"
-  printf "  \033[1m-f, --format\033[0m <format>\tSpecify the output image format (png, jpg, webp)\n\n"
+  printf "  \033[1m--help, -h\033[0m\t\tDisplay this help message and exit\n"
+  printf "  \033[1m--format, -f\033[0m <format>\tSpecify the output image format (png, jpg, webp)\n\n"
   printf "\033[1m\033[4mExamples:\033[0m\n"
   printf '  $ convert_img -f png image.jpg\n'
   printf '  $ convert_img *.jpg -f png\n'
@@ -23,6 +23,7 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
   exit 0
 fi
 
+require=("magick")
 format="jpg" # Default format
 input_files=()
 
@@ -67,10 +68,12 @@ convert() {
   magick "$filename" "$output"
 }
 
-if ! command -v magick &>/dev/null; then
-  echo "Error: 'convert' command not found. Please install ImageMagick."
-  exit 1
-fi
+for cmd in "${require[@]}"; do
+  if ! command -v "$cmd" &>/dev/null; then
+    echo "Error: Required command '$cmd' not found. Please install it."
+    exit 1
+  fi
+done
 
 for file in "${input_files[@]}"; do
   echo "Converting '$file' ..."
diff --git a/home/dot_config/scripts/executable_miniimg b/home/dot_config/scripts/executable_miniimg
--- a/home/dot_config/scripts/executable_miniimg
+++ b/home/dot_config/scripts/executable_miniimg
@@ -5,10 +5,11 @@ set -euo pipefail
 help() {
   printf "\033[1mUsage: miniimg\033[0m [OPTIONS] <files>\n\n"
   printf "\033[1m\033[4mOptions:\033[0m\n"
-  printf "  \033[1m-l, --lossy\033[0m         Enable lossy compression (default: lossless)\n"
-  printf "  \033[1m-q, --quality <q>\033[0m   Set the quality of the output image (0-100, default: 75)\n"
-  printf "  \033[1m-o, --output <file>\033[0m Specify the output file name\n"
-  printf "  \033[1m-h, --help\033[0m          Show this help message\n\n"
+  printf "  \033[1m--lossy, -l\033[0m         Enable lossy compression (default: lossless)\n"
+  printf "  \033[1m--quality, -q <q>\033[0m   Set the quality of the output image (0-100, default: 75)\n"
+  printf "  \033[1m--output, -o <file>\033[0m Specify the output file name\n"
+  printf "  \033[1m--preview, -p\033[0m       Show a preview of the original and optimized images\n"
+  printf "  \033[1m--help, -h\033[0m          Show this help message\n\n"
   printf "\033[1m\033[4mExamples:\033[0m\n"
   printf '  $ miniimg input.png\n'
   printf '  $ miniimg *.jpg\n'
@@ -26,6 +27,8 @@ if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
   exit 0
 fi
 
+require=("pngquant" "oxipng" "jpegoptim")
+preview=false
 lossy=false
 quality=75
 input_files=()
@@ -53,6 +56,9 @@ while [ $# -gt 0 ]; do
       fi
       output="$1"
       ;;
+    -p | --preview)
+      preview=true
+      ;;
     -*)
       echo "Error: Unknown option $1"
       help
@@ -71,7 +77,7 @@ compress() {
     exit 1
   fi
 
-  if [ ! -d "$OUT_DIR" ]; then
+  if [ -z "$output" ] && [ ! -d "$OUT_DIR" ]; then
     mkdir -p "$OUT_DIR"
   fi
 
@@ -88,15 +94,18 @@ compress() {
       fi
       ;;
     jpg | jpeg)
-      if [ "$lossy" = true ]; then
-        jpegoptim -m "$quality" "$1" --strip-all -o -d "$OUT_DIR"
-      else
-        jpegoptim "$1" --strip-all -o -d "$OUT_DIR"
+      local dest=""
+      if [ -z "$output" ]; then
+        dest="-d $OUT_DIR"
       fi
 
-      # check if there's no error, and if so, rename the output
-      # to match the provided output name
-      if [ -n "$OUT_DIR/$1" ]; then
+      if [ "$lossy" = true ]; then
+        jpegoptim -m "$quality" "$1" --strip-all -o "$dest"
+      else
+        jpegoptim "$1" --strip-all -o "$dest"
+      fi
+
+      if [ -z $output ] && [ -n "$OUT_DIR/$1" ]; then
         mv "$OUT_DIR/$1" "$output"
       fi
       ;;
@@ -106,7 +115,9 @@ compress() {
       ;;
   esac
 
-  compare "$1" "$output"
+  if [ "$preview" = true ]; then
+    compare "$1" "$output"
+  fi
 }
 
 compare() {
@@ -115,7 +126,10 @@ compare() {
     exit 1
   fi
 
-  chafa "$1" "$2"
+  echo "Original: $1"
+  chafa "$1" -s 40x20
+  echo "Optimized: $2"
+  chafa "$2" -s 40x20
 }
 
 if [ ${#input_files[@]} -eq 0 ]; then
@@ -123,6 +137,13 @@ if [ ${#input_files[@]} -eq 0 ]; then
   help
   exit 1
 fi
+
+for cmd in "${require[@]}"; do
+  if ! command -v "$cmd" &>/dev/null; then
+    echo "Error: Required command '$cmd' is not installed."
+    exit 1
+  fi
+done
 
 for file in "${input_files[@]}"; do
   compress "$file"
